#:schema ../../packages/logger/gitcord-logger.schema.json

[logger]
level           = "DEBUG"
timestampFormat = "ISO"

[logger.colors]
# Colors can be specified as 24-bit hex strings or integer values
debug = "#00bfff"
info  = "#32cd32"
warn  = "#ffd700"
error = "#ff4500"
